name: Build on new Draft

permissions:
  contents: write

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build Release
        if: matrix.build == 'release'
        run: pyinstaller --onefile --noconsole --name Windows-Player player.py

      - name: Build Debug
        if: matrix.build == 'debug'
        run: pyinstaller --onefile --name Windows-Player-Debug player.py

      - name: Save
        if: matrix.build == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/win
      - name: Save
        if: matrix.build == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: dist/win

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        build: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build Release
        if: matrix.build == 'release'
        run: pyinstaller --onefile --windowed --target-architecture universal2 --name MacOS-Player player.py

      - name: Build Debug
        if: matrix.build == 'debug'
        run: pyinstaller --onefile --target-architecture universal2 --name MacOS-Player-Debug player.py

      - name: Save
        if: matrix.build == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/mac
      - name: Save
        if: matrix.build == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: dist/mac
          

  publish:
    runs-on: windows-latest
    needs: [build-win, build-mac]
    if: success()

    steps:
      - uses: actions/checkout@v4
    
      - name: Get Files
        uses: actions/download-artifact@v4
    
      - name: Upload to Draft
        uses: softprops/action-gh-release@v2
        with:
          files: |
            win/build/Windows-Player.exe
            win/debug/Windows-Player-Debug.exe
            mac/build/MacOS-Player.exe
            mac/debug/MacOS-Player-Debug.exe
            player.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
