name: Build EXE

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build Release
        if: matrix.build == 'release'
        run: pyinstaller --onefile --noconsole --name Player player.py

      - name: Build Debug
        if: matrix.build == 'debug'
        run: pyinstaller --onefile --name Player-Debug player.py

      - name: Save
        if: matrix.build == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
      - name: Save
        if: matrix.build == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: dist/
          

  publish:
    runs-on: windows-latest
    needs: [build]
    if: success()

    steps:
      - uses: actions/checkout@v4
    
      - name: Get Files
        uses: actions/download-artifact@v4
    
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: true
          files: |
            build/Player.exe
            debug/Player-Debug.exe
            player.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
